server:
  port: 8080
spring:
  application:
    name: demoMybatisPlus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: master
    url: jdbc:mysql://localhost:3306/world?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&profileSQL=false&profilerEventHandler=com.example.demoMybatisPlus.config.eventHandler.ProfileSQLHandler
    username: root
    password: admin
  sql:
    init:
      mode: never  #改成always,自动执行sql创建表和初始化数据
mybatis-plus:
  configuration:
    jdbc-type-for-null: 'null'
    call-setters-on-nulls: true
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    #比如数据库中的字段名是id_number        对应的实体类的名字是idNumber
    map-underscore-to-camel-case: true
    #加上这个配置就可以打印sql语句  yaml里是自动配置，自己手动定义的数据源不会打印sql,需要在config类里再定义一遍
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  compression:
    request:
      min-request-size: 8092
  api:
    deliver-url: "https://hmls.haier.net/delivery-intern-api"
    hdy-url: "http://l.ihaier.com"
    thirdparty-url: "http://haier-thirdparty/open-api"
    wms-url: "http://haier-raw-wms-service/wms-api"
    vmi-url: "http://haier-raw-vmi-service/vmi-api"
    bms-url: "http://haier-raw-bms-service/bms-api"
  client:
    config:
      default: # 服务名，填写 default 为所有服务，或者指定某服务，例如：annoroad-beta
        connectTimeout: 10000 # 连接超时，10秒
        readTimeout: 120000 # 读取超时，120秒
    httpclient:
      enabled: false # 关闭 ApacheHttpClient
      max-connections: 50 # 连接池连接最大连接数（缺省值 200）
      time-to-live: 600 # 连接最大闲置时间，单位为秒，600秒==10分钟（缺省值为 900秒==15分钟）
    okhttp:
      enabled: true # 开启 okhttp